---
# tasks file for mysql

- name: Get mysql source code
  git:
    repo: https://github.com/mysql/mysql-server.git
    dest: "{{ tmp_path }}"
    depth: 1
    version: "mysql-{{ mysql_version }}"

- name: Ensure build folder is present
  file:
    path: "{{ tmp_path }}/build"
    state: directory

- name: Install mysql
  command: "{{ item }}"
  args:
    chdir: "{{ tmp_path }}/build"
    creates: "{{ mysql_path }}"
  with_items:
    - >
      cmake .. -DCMAKE_INSTALL_PREFIX={{ mysql_path }}
      -DWITH_SYSTEMD=1 -DSYSTEMD_SERVICE_NAME={{ mysql_service_name }}
      -DMYSQL_DATADIR={{ mysql_data_dir }} -DMYSQL_TCP_PORT={{ mysql_port }}
      -DMYSQL_UNIX_ADDR={{ mysql_unix_address }}
      {{ cmake_extra_args }}
    - make
    - make install

- name: Create mysql service
  template:
    src: "mysql.service.j2"
    dest: "/etc/systemd/system/{{ mysql_service_name }}.service"
    mode: 0664

- name: Add mysql bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/mysql.sh
    content: 'PATH=$PATH:{{ mysql_path }}/bin'

- name: Ensure mysql service is enabled and started
  systemd:
    daemon_reload: true
    name: "{{ mysql_service_name }}"
    state: started
    enabled: true
